// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/serialreader.proto

package serialreader_server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SerialReaderClient is the client API for SerialReader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SerialReaderClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	GetSparkFunWeatherShieldData(ctx context.Context, in *GetTimeSeriesData, opts ...grpc.CallOption) (*SparkFunWeatherShieldTimeSeriesData, error)
}

type serialReaderClient struct {
	cc grpc.ClientConnInterface
}

func NewSerialReaderClient(cc grpc.ClientConnInterface) SerialReaderClient {
	return &serialReaderClient{cc}
}

func (c *serialReaderClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/proto.SerialReader/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serialReaderClient) GetSparkFunWeatherShieldData(ctx context.Context, in *GetTimeSeriesData, opts ...grpc.CallOption) (*SparkFunWeatherShieldTimeSeriesData, error) {
	out := new(SparkFunWeatherShieldTimeSeriesData)
	err := c.cc.Invoke(ctx, "/proto.SerialReader/GetSparkFunWeatherShieldData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SerialReaderServer is the server API for SerialReader service.
// All implementations must embed UnimplementedSerialReaderServer
// for forward compatibility
type SerialReaderServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	GetSparkFunWeatherShieldData(context.Context, *GetTimeSeriesData) (*SparkFunWeatherShieldTimeSeriesData, error)
	mustEmbedUnimplementedSerialReaderServer()
}

// UnimplementedSerialReaderServer must be embedded to have forward compatible implementations.
type UnimplementedSerialReaderServer struct {
}

func (UnimplementedSerialReaderServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedSerialReaderServer) GetSparkFunWeatherShieldData(context.Context, *GetTimeSeriesData) (*SparkFunWeatherShieldTimeSeriesData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSparkFunWeatherShieldData not implemented")
}
func (UnimplementedSerialReaderServer) mustEmbedUnimplementedSerialReaderServer() {}

// UnsafeSerialReaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SerialReaderServer will
// result in compilation errors.
type UnsafeSerialReaderServer interface {
	mustEmbedUnimplementedSerialReaderServer()
}

func RegisterSerialReaderServer(s grpc.ServiceRegistrar, srv SerialReaderServer) {
	s.RegisterService(&SerialReader_ServiceDesc, srv)
}

func _SerialReader_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerialReaderServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SerialReader/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerialReaderServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SerialReader_GetSparkFunWeatherShieldData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTimeSeriesData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerialReaderServer).GetSparkFunWeatherShieldData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SerialReader/GetSparkFunWeatherShieldData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerialReaderServer).GetSparkFunWeatherShieldData(ctx, req.(*GetTimeSeriesData))
	}
	return interceptor(ctx, in, info, handler)
}

// SerialReader_ServiceDesc is the grpc.ServiceDesc for SerialReader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SerialReader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SerialReader",
	HandlerType: (*SerialReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _SerialReader_SayHello_Handler,
		},
		{
			MethodName: "GetSparkFunWeatherShieldData",
			Handler:    _SerialReader_GetSparkFunWeatherShieldData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/serialreader.proto",
}
